### ISSUE TITLE
Installation / Pre-Requisite instructions unclear

### ISSUE THREAD

**Issue by MaikNog** [MaibornWolff/TestVille#6]
I followed the instructions on https://maibornwolff.github.io/TestVille/ ==> ./gradlew   build
With the message "No Java runtime present, requesting install." I installed the JDK and JRE for macOS.

Maybe I am missing more tools installed? It fails with this:

```
Downloads/TestVille-1.0.0 $ ./gradlew build

> Task :analysis:junitPlatformTest FAILED
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:510)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:522)
Caused by: java.lang.RuntimeException: Class java/lang/UnknownError could not be instrumented.
        at org.jacoco.agent.rt.internal_290345e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:139)
        at org.jacoco.agent.rt.internal_290345e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:100)
        at org.jacoco.agent.rt.internal_290345e.PreMain.createRuntime(PreMain.java:55)
        at org.jacoco.agent.rt.internal_290345e.PreMain.premain(PreMain.java:47)
        ... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
FATAL ERROR in native method: processing of -javaagent failed
        at java.base/java.lang.Class.getField(Class.java:1958)
        at org.jacoco.agent.rt.internal_290345e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:137)
        ... 9 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':analysis:junitPlatformTest'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home/bin/java'' finished with non-zero exit value 134

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
6 actionable tasks: 1 executed, 5 up-to-date
```

**Comment by CarinSchreiner** [comment]
Hey @MaikNog,
did you installed JDK9?

**Comment by MaikNog** [comment]
Hi @CarinSchreiner ,
sorry for belated reply. I installed the latest versions for MacOX; JRE and JDK 10 versions.

**Comment by jniada** [comment]
Hi @MaikNog, 
the  [build script](https://github.com/MaibornWolff/TestVille/blob/master/analysis/build.gradle) is configured to build the `analysis-module` with JDK9. You must install JDK9 to install the project.
